# @package _global_

training:
  training_backend: mcore
  use_gen_rm_reward: False
  use_bt_rm_reward: True
  use_fast_tokenizer: True
  rollout_gbs: 64
  rollout_mbs: 1
  sampling_repeat_n: 16
  sampling_keep_n: 16
  train_gbs: 256
  train_mbs: 1
  data_parallel_random_init: False
  save_interval: 100
  eval_interval: 5
  eval_before_train: False
  build_from_mbridge: True
  num_train_epoches: 2
  ppo_max_epochs_2: 2
  metrics_report:
    - "acc_reward"
    - "fmt_reward"

checkpoint:
  load_ckpt_path: save_qwen_2_5_1_5b_gdpo_sample_bn
  save_ckpt_path: save_qwen_2_5_1_5b_gdpo_sample_bn
  convert_mcore_to_hf_online: True
  mbridge_distributed_filesystem: True

optimizer:
  lr: 5.0e-7
  lr_warmup_steps: 2
  lr_decay_style: "cosine"
  weight_decay: 0.0
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1.0e-8

data:
  data_pathes:
    - "hf-hub/openai/gsm8k-jsonl/train"
  eval_data_pathes:
    - "hf-hub/openai/gsm8k-jsonl/eval"

  py_path: "tasks/math_rl_v4/simple_dataset.py"
  system_prompt: "Please reason step by step, keep your reasoning as short as possible, and put your final answer within \\boxed{}."
  fn_name: "get_dataset_and_dataloader"
  dataloader_num_workers: 1
  dataloader_pin_memory: True

policy:
  dist_config:
    tensor_model_parallel_size: 2
    pipeline_model_parallel_size: 2
  model_arch: qwen2
  hf_model_path: "sft_convert/hf/3357/"
  hf_tokenizer_path: "sft_convert/hf/3357/"
  ref_hf_model_path: "sft_convert/hf/3357/"
  sampler_client:
    rpc_type: ray
  gen_rm_client:
    rpc_type: ray
  bt_rm_client:
    rpc_type: ray

sampler:
  backend: sglang
  model_info:
    - model_arch: qwen2
      hf_model_path: "sft_convert/hf/3357/"

  infer_engine_configs:
    - dist_config:
        tensor_model_parallel_size: 2
      use_fast_tokenizer: True
      gpu_memory_utilization: 0.7
      max_running_requests: 128
      temperature: 1.0
      top_p: 0.9
      generate_max_tokens: 1024

bt_rm:
  reward_type: "rule_only"
  reward_model_info:
    - model_arch: "qwen2.5-math-rm-72b"
      hf_model_path: "hf-hub/Qwen/Qwen2.5-Math-RM-72B/"
      reward_py_path: tasks/math_rl_v4/bt_reward.py
      parse_reward_fn_name: math_rl_rule_reward
      reward_weight: 1.0
  infer_engine_configs:
    - dist_config:
        nnodes: -1

# dist_config.nnodes 设置 -1 表示适用所有节点

ppo:
  advantage_type: "group_gdpo_sample_bn"
  gdpo_reward_weights:
    acc_reward: 1.0
    fmt_reward: 1.0
  grpo_advantage_epsilon: 1.0e-4
  ppo_ratio_eps: 0.2

debug:
  save_first_rollout_data: True
  debug_engine_update_weight: False
