# @package _global_

training:
  training_backend: mcore
  use_gen_rm_reward: False
  use_bt_rm_reward: True
  use_fast_tokenizer: True
  rollout_gbs: 512
  rollout_mbs: 1
  sampling_repeat_n: 8
  sampling_keep_n: 8
  train_gbs: 256
  train_mbs: 8
  data_parallel_random_init: False
  save_interval: 1000
  eval_interval: 0
  eval_before_train: False
  build_from_mbridge: True
  num_train_epoches: 10
  ppo_max_epochs_2: 1
  seq_length: 4096
  metrics_report:
    - "acc_reward"

checkpoint:
  load_ckpt_path: null
  save_ckpt_path: qwen2_5_math_7b_steer_verl_aligned
  convert_mcore_to_hf_online: True
  mbridge_distributed_filesystem: True

optimizer:
  lr: 1.0e-6
  lr_warmup_steps: 0
  lr_decay_style: "constant"
  weight_decay: 0.01
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1.0e-8

data:
  data_pathes:
    - "hf-hub/zhuzilin/dapo-math-17k/"
  py_path: "tasks/math_rl_v4/dapo_dataset.py"
  fn_name: "get_dataset_and_dataloader"
  system_prompt: null
  dataloader_num_workers: 1
  dataloader_pin_memory: True

policy:
  dist_config:
    tensor_model_parallel_size: 2
    pipeline_model_parallel_size: 1
  model_arch: qwen2
  forward_only_mbs: 8
  hf_model_path: "hf-hub/Qwen/Qwen2.5-Math-7B"
  hf_tokenizer_path: "hf-hub/Qwen/Qwen2.5-Math-7B"
  ref_hf_model_path: "hf-hub/Qwen/Qwen2.5-Math-7B"
  without_ref: True
  sampler_client:
    rpc_type: ray
  gen_rm_client:
    rpc_type: ray
  bt_rm_client:
    rpc_type: ray
  balance_dp_seqlen: True
  smart_pad_infer: True
  smart_pad_train: True
  override_transformer_config:
    calculate_per_token_loss: true
    recompute_granularity: full
    recompute_method: uniform
    recompute_num_layers: 1

sampler:
  backend: sglang
  model_info:
    - model_arch: qwen2
      hf_model_path: "hf-hub/Qwen/Qwen2.5-Math-7B"
  infer_engine_configs:
    - dist_config:
        tensor_model_parallel_size: 2
      use_fast_tokenizer: True
      gpu_memory_utilization: 0.6
      max_running_requests: 128
      temperature: 1.0
      top_p: 1.0
      generate_max_tokens: 3072

bt_rm:
  reward_type: "rule_only"
  reward_model_info:
    - model_arch: "qwen2"
      hf_model_path: "hf-hub/Qwen/Qwen2.5-Math-7B"
      reward_py_path: tasks/math_rl_v4/bt_reward_algin_steer.py
      parse_reward_fn_name: dapo_math_strict_box_reward
      reward_weight: 1.0
  infer_engine_configs:
    - dist_config:
        nnodes: -1

ppo:
  advantage_type: "grpo"
  loss_func: "steer"
  use_legacy_loss: False
  steer_token_weight_min: 0.8
  steer_policy_method: "grpo"
  grpo_advantage_epsilon: 1.0e-6
  grpo_kl_loss_beta: 0.0
  ppo_ratio_eps: 0.0
  ppo_clip_ratio_low: 0.2
  ppo_clip_ratio_high: 0.28
  ppo_dual_clip_ratio_c: 10.0
  ppo_entropy_bonus: 0.0
  ppo_logps_ratio_clamp: 20.0

debug:
  save_first_rollout_data: True
  debug_engine_update_weight: False
