data:
  data_pathes:
    - "hf-hub/openai/gsm8k-jsonl/eval"
  py_path: "tasks/infer_only/simple_dataset.py"
  fn_name: "get_dataset_and_dataloader"
  dataloader_num_workers: 1
  dataloader_pin_memory: True

sampler:
  backend: sglang
  sampler_type: "sampler"
  dist_config:
    nnodes: 4
    num_gpus_per_node: 8
  model_info:
    - model_arch: "qwen3_5"
      hf_model_path: hf-hub/Qwen/Qwen3.5-27B
      gen_rollout_py_path: "tasks/infer_only/sample_demo.py"
      gen_rollout_fn_name: "generate_func"

  infer_engine_configs:
    - dist_config:
        nnodes: 4
        tensor_model_parallel_size: 8
        num_gpus_per_node: 8
      gpu_memory_utilization: 0.8
      max_running_requests: 64
      temperature: 0.7
      top_k: 40
      top_p: 0.9
      generate_max_tokens: 7168
      use_fast_tokenizer: False

infer_result:
  output_dir: "infer_only_results/qw35_27B"
