# @package _global_
_target_: gpatch_v4.configs.config.FinetuneConfig

training:
  training_backend: fsdp2
  use_fast_tokenizer: True
  train_gbs: 32
  train_mbs: 1
  seq_length: 2048
  data_parallel_random_init: False
  save_interval: 10
  num_train_epoches: 1
  comput_attn_mask: False
  sort_batched: False
  auto_load_from_save_ckpt: True
  use_dynamic_mbs: True

checkpoint:
  load_ckpt_path: ckpt_gemma4_sft
  save_ckpt_path: ckpt_gemma4_sft
  convert_mcore_to_hf_online: True
  mbridge_distributed_filesystem: True

optimizer:
  lr: 5.0e-7
  lr_warmup_steps: 0
  lr_decay_style: "constant"
  weight_decay: 0.0
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1.0e-8

data:
  data_pathes:
    # 为了快速测试，这里只 load 一个文件，也可以加上多个文件
    - "hf-hub/BUAADreamer/llava-en-zh-300k/zh/train-00000-of-00059.parquet"
  py_path: "tasks/multimodal_v4/finetune/gemma4_sft_dataset.py"
  fn_name: "get_dataset_and_dataloader"
  dataloader_num_workers: 2
  dataloader_pin_memory: True
  dataloader_verify_fn_name: "verify_dataloader_func"

policy:
  dist_config:
    tensor_model_parallel_size: 1
    pipeline_model_parallel_size: 1
  manual_clear_memory: False
  model_arch: "gemma4"
  without_ref: True
  attn_implementation: "sdpa"
  hf_model_path: "hf-hub/google/gemma-4-E4B-it"
  hf_tokenizer_path: "hf-hub/google/gemma-4-E4B-it"

debug:
  save_first_rollout_data: True
