# @package _global_
_target_: gpatch_v4.configs.config.FinetuneConfig

training:
  training_backend: mcore
  use_fast_tokenizer: True
  train_gbs: 256
  train_mbs: 1
  seq_length: 4096
  data_parallel_random_init: False
  save_interval: 100
  num_train_epoches: 1
  comput_attn_mask: False
  sort_batched: False
  auto_load_from_save_ckpt: True
  build_from_mbridge: True
  use_dynamic_mbs: True

checkpoint:
  load_ckpt_path: ckpt_qwen3_vl_llava
  save_ckpt_path: ckpt_qwen3_vl_llava
  convert_mcore_to_hf_online: True
  mbridge_distributed_filesystem: True

optimizer:
  lr: 5.0e-7
  lr_warmup_steps: 0
  lr_decay_style: "constant"
  weight_decay: 0.0
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1.0e-8

data:
  data_pathes:
    # 为了快速测试，这里只 load 一个文件，也可以加上多个文件
    - "hf-hub/BUAADreamer/llava-en-zh-300k/zh/train-00000-of-00059.parquet"
  py_path: "tasks/multimodal_v4/finetune/qwen3vl_sft_multi_turn.py"
  fn_name: "get_dataset_and_dataloader"
  dataloader_num_workers: 4
  dataloader_pin_memory: True
  dataloader_verify_fn_name: "verify_dataloader_func"

policy:
  dist_config:
    tensor_model_parallel_size: 2
    pipeline_model_parallel_size: 2
  manual_clear_memory: False
  model_arch: "qwen3_vl"
  without_ref: True
  hf_model_path: "hf-hub/Qwen/Qwen3-VL-4B-Instruct"
  hf_tokenizer_path: "hf-hub/Qwen/Qwen3-VL-4B-Instruct"

debug:
  save_first_rollout_data: True
