_target_: gpatch_v4.configs.config.EvaluateConfig

training:
  seq_length: 8192
  train_mbs: 1
  use_fast_tokenizer: True
  eval_sampling_repeat_n: 8

data:
  data_pathes:
    - "hf-hub/hiyouga/geometry3k"
  py_path: "tasks/multimodal_v4/off_policy_distill/qwen3vl_gen_dataset.py"
  fn_name: "get_dataset_and_dataloader"
  dataloader_num_workers: 4
  dataloader_pin_memory: True
  # only for verify dataloader in gpatch_v4/entry/verify_dataloader.py
  dataloader_verify_fn_name: "verify_dataloader_func"

policy:
  dist_config:
    nnodes: -1
  model_arch: "qwen3_vl"
  hf_tokenizer_path: "hf-hub/Qwen/Qwen3-VL-2B-Instruct"
  sampler_client:
    rpc_type: ray

sampler:
  backend: sglang
  sampler_type: "sampler"
  dist_config:
    nnodes: -1
  model_info:
    - model_arch: "qwen3_vl"
      hf_model_path: "hf-hub/Qwen/Qwen3-VL-2B-Instruct"
      gen_rollout_py_path: "tasks/multimodal_v4/off_policy_distill/offline_generate_examples.py"
      gen_rollout_fn_name: "offline_generate_func"

  infer_engine_configs:
    - dist_config:
        nnodes: -1
        tensor_model_parallel_size: 2
      gpu_memory_utilization: 0.7
      max_running_requests: 128
      mm_per_request_timeout: 100
      temperature: 1.0
      top_p: 0.9
      generate_max_tokens: 7168
      use_fast_tokenizer: True

evaluate_result:
  evaluate_py_path: tasks/multimodal_v4/off_policy_distill/offline_generate_examples.py
  evaluate_fn_name: eval_rollout_samples

task:
  dataset_key: "test"
