# https://github.com/SalesforceAIResearch/DiffusionDPO/blob/main/README.md
MODEL_NAME: xxx
DATASET_NAME: xxx
trainer:
  _target_: tasks.t2i_dpo.oteam_44.oteam.OteamDpoTrainer
  # dpo training config
  args:
    training:
      pretrained_model_name_or_path: ${MODEL_NAME}
      train_batch_size: 1
      mixed_precision: "bf16"
      gradient_accumulation_steps: 1
      max_train_steps: 10000
      scale_lr: True
      max_prompt_length: 256
      guidance_scale: 1.
      recompute: True
      save_interval: 10000
    data:
      dataset_name: ${DATASET_NAME}
      dataloader_num_workers: 16
      cache_dir: "./pick_a_pic_v2/"
    checkpoint:
      load_ckpt_path: t2i_grpo_tv4_oteam4_4_save
      save_ckpt_path: t2i_grpo_tv4_oteam4_4_save
    optimizer:
      lr: 1e-8
      lr_warmup_steps: 500
      lr_decay_style: "constant_with_warmup"
      weight_decay: 0.0001
      max_grad_norm: 1.0
    ppo:
      beta_dpo: 5000
    policy:
      dist_config:
        nnodes: 8
      without_ref: false
      model_arch: "oteam4_4"
      hf_model_path: "hf-hub/wechat/oteam4_4-step-10000"
      ref_hf_model_path: "hf-hub/wechat/oteam4_4-step-10000"
