# @package _global_

training:
  training_backend: mcore
  use_fast_tokenizer: True
  train_gbs: 32
  train_mbs: 1
  seq_length: 4096
  data_parallel_random_init: False
  save_interval: 10000
  num_train_epoches: 1
  comput_attn_mask: True
  sort_batched: False
  auto_load_from_save_ckpt: True
  pad_to_mulitiple_of: 128
  use_dynamic_mbs: True
  moe_pad_with_random_tokens: True
  freeze_moe_router: True
  attention_backend: fused

policy:
  dist_config:
    tensor_model_parallel_size: 8
    pipeline_model_parallel_size: 1
    expert_model_parallel_size: 32
    expert_tensor_parallel_size: 1
    context_parallel_size: 2
  model_arch: "welmv4_moe"
  without_ref: True
  post_wrap_with_ddp: True
  hf_model_path: "hf-hub/wechat/WeLM-v4.5"
  hf_tokenizer_path: "hf-hub/wechat/WeLM-v4.5"
  override_transformer_config:
    variable_seq_lengths: False
    moe_router_load_balancing_type: "none"
    moe_aux_loss_coeff: 0.0
    recompute_granularity: full
    recompute_method: uniform
    recompute_num_layers: 1
    cp_comm_type: all_gather
    fallback_to_eager_attn: True

checkpoint:
  load_ckpt_path: save_welm_v4_5_sft_cp2
  save_ckpt_path: save_welm_v4_5_sft_cp2
  save_total_limit: 5
  save_retain_interval: 5000
  convert_mcore_to_hf_online: True
  mbridge_distributed_filesystem: True

optimizer:
  lr: 2.0e-5
  lr_warmup_steps: 200
  lr_decay_style: "cosine"
  weight_decay: 0.0
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1.0e-8

data:
  data_pathes:
    - "hf-hub/AI-MO/NuminaMath-CoT-jsonl/train/"
  py_path: "tasks/math_rl_v4/finetune_dataset.py"
  fn_name: "get_dataset_and_dataloader"
  system_prompt: "Please reason step by step, keep your reasoning as short as possible, and put your final answer within \\boxed{}."
  dataloader_num_workers: 1
  dataloader_pin_memory: True

debug:
  save_first_rollout_data: True
  experimental_pad_to_max_length: False
