# @package _global_

training:
  training_backend: mcore
  use_gen_rm_reward: False
  use_bt_rm_reward: True
  use_fast_tokenizer: True
  rollout_gbs: 64
  rollout_mbs: 1
  sampling_repeat_n: 16
  sampling_keep_n: 16
  train_gbs: 256
  train_mbs: 1
  data_parallel_random_init: False
  save_interval: 100
  auto_load_from_save_ckpt: True
  build_from_mbridge: True
  num_train_epoches: 2
  ppo_max_epochs_2: 2
  metrics_report:
    - "acc_reward"
    - "fmt_reward"
  enable_mtp: true
  online_mtp_sft: true

checkpoint:
  load_ckpt_path: ckpt_qwen3_5_4b_gdpo_text_only
  save_ckpt_path: ckpt_qwen3_5_4b_gdpo_text_only
  convert_mcore_to_hf_online: True
  mbridge_distributed_filesystem: True

optimizer:
  lr: 5.0e-7
  lr_warmup_steps: 2
  lr_decay_style: "cosine"
  weight_decay: 0.0
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1.0e-8

data:
  data_pathes:
    - "hf-hub/openai/gsm8k-jsonl/train"
  py_path: "tasks/multimodal_v4/grpo/qwenvl_text_only_dataset.py"
  fn_name: "get_dataset_and_dataloader"
  system_prompt: "Please reason step by step, keep your reasoning as short as possible, and put your final answer within \\boxed{}."
  dataloader_num_workers: 1
  dataloader_pin_memory: True
  dataloader_verify_fn_name: "verify_dataloader_func"

policy:
  dist_config:
    tensor_model_parallel_size: 2
    pipeline_model_parallel_size: 2
  model_arch: qwen3_5
  hf_model_path: "hf-hub/Qwen/Qwen3.5-4B"
  hf_tokenizer_path: "hf-hub/Qwen/Qwen3.5-4B"
  ref_hf_model_path: "hf-hub/Qwen/Qwen3.5-4B"
  forward_only_mbs: 1
  rollout_gen_type: "base"
  sampler_client:
    rpc_type: ray
  gen_rm_client:
    rpc_type: ray
  bt_rm_client:
    rpc_type: ray
  balance_dp_seqlen: True
  smart_pad_infer: True
  smart_pad_train: True
  dynamic_mbs_target_seqlen_fwd_only: 8192
  dynamic_mbs_limit_fwd_only: 16
  dynamic_mbs_target_seqlen: 4096
  dynamic_mbs_limit: 16

sampler:
  backend: sglang
  model_info:
    - model_arch: qwen3_5
      hf_model_path: "hf-hub/Qwen/Qwen3.5-4B"

  infer_engine_configs:
    - dist_config:
        tensor_model_parallel_size: 2
      use_fast_tokenizer: True
      gpu_memory_utilization: 0.7
      max_running_requests: 128
      temperature: 1.0
      top_p: 0.9
      generate_max_tokens: 1024
      sgl_mamba_scheduler_strategy: extra_buffer
      sgl_enable_spec_v2: true
      override_infer_engine_config:
        speculative_num_steps: 3
        speculative_eagle_topk: 1
        speculative_num_draft_tokens: 4
        speculative_algorithm: EAGLE
        skip_server_warmup: true

bt_rm:
  reward_type: "rule_only"
  reward_model_info:
    - model_arch: "qwen3_5"
      hf_model_path: "hf-hub/Qwen/Qwen3.5-4B"
      reward_py_path: tasks/math_rl_v4/bt_reward.py
      parse_reward_fn_name: math_rl_rule_reward
      reward_weight: 1.0
  infer_engine_configs:
    - dist_config:
        nnodes: -1

# dist_config.nnodes 设置 -1 表示适用所有节点

ppo:
  advantage_type: "custom_gdpo_sample_bn_dead_mask"
  custom_advantage_py_path: "tasks/math_rl_v4/custom_gdpo_dead_mask_advantage.py"
  custom_advantage_py_name: "compute_gdpo_sample_bn_dead_mask_advantages"
  custom_post_advantage_py_name: "gdpo_sample_bn_dead_mask_post_advantage"
  gdpo_reward_weights:
    acc_reward: 1.0
    fmt_reward: 1.0
  grpo_advantage_epsilon: 1.0e-4
  ppo_ratio_eps: 0.2

task:
  dead_group_threshold: 0.01

debug:
  save_first_rollout_data: True
  debug_engine_update_weight: False
