# @package _global_

training:
  training_backend: mcore
  use_gen_rm_reward: False
  use_bt_rm_reward: True
  use_fast_tokenizer: True
  rollout_gbs: 256
  rollout_mbs: 1
  sampling_repeat_n: 32
  sampling_keep_n: 32
  train_gbs: 256
  train_mbs: 1
  seq_length: 4096
  data_parallel_random_init: False
  save_interval: 100
  auto_load_from_save_ckpt: True
  build_from_mbridge: True
  num_train_epoches: 2
  ppo_max_epochs_2: 2
  moe_pad_with_random_tokens: True
  load_aware_sampler_routing: True
  load_aware_sampler_dispatch_stagger_s: 0.1
  freeze_moe_router: True
  freeze_vit: True
  freeze_projector: True
  metrics_report:
    - "acc_reward"
    - "fmt_reward"

checkpoint:
  load_ckpt_path: ckpt_qwen3_6_35b_grpo_text_only
  save_ckpt_path: ckpt_qwen3_6_35b_grpo_text_only
  convert_mcore_to_hf_online: True
  mbridge_distributed_filesystem: True

optimizer:
  lr: 5.0e-7
  lr_warmup_step_frac: 0.02
  lr_decay_style: "cosine"
  weight_decay: 0.0
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1.0e-8

data:
  data_pathes:
    - "hf-hub/openai/gsm8k-jsonl/train"
  py_path: "tasks/multimodal_v4/grpo/qwenvl_text_only_dataset.py"
  fn_name: "get_dataset_and_dataloader"
  system_prompt: "Please reason step by step, keep your reasoning as short as possible, and put your final answer within \\boxed{}."
  dataloader_num_workers: 1
  dataloader_pin_memory: True
  dataloader_verify_fn_name: "verify_dataloader_func"

policy:
  dist_config:
    num_gpus_per_node: 8
    tensor_model_parallel_size: 2
    pipeline_model_parallel_size: 2
    expert_model_parallel_size: 4
    expert_tensor_parallel_size: 1
    context_parallel_size: 1

  model_arch: qwen3_5_moe
  hf_model_path: "hf-hub/Qwen/Qwen3.6-35B-A3B/"
  hf_tokenizer_path: "hf-hub/Qwen/Qwen3.6-35B-A3B/"
  ref_hf_model_path: "hf-hub/Qwen/Qwen3.6-35B-A3B/"
  forward_only_mbs: 1
  rollout_gen_type: "base"
  sampler_client:
    rpc_type: ray
  gen_rm_client:
    rpc_type: ray
  bt_rm_client:
    rpc_type: ray
  balance_dp_seqlen: True
  smart_pad_infer: True
  smart_pad_train: True
  dynamic_mbs_target_seqlen_fwd_only: 8192
  dynamic_mbs_limit_fwd_only: 16
  dynamic_mbs_target_seqlen: 4096
  dynamic_mbs_limit: 16
  override_transformer_config:
    variable_seq_lengths: False
    moe_router_load_balancing_type: "none"
    moe_aux_loss_coeff: 0.0
    recompute_granularity: full
    recompute_method: uniform
    recompute_num_layers: 1

sampler:
  backend: vllm
  model_info:
    - model_arch: qwen3_5_moe
      hf_model_path: "hf-hub/Qwen/Qwen3.6-35B-A3B/"

  infer_engine_configs:
    - dist_config:
        tensor_model_parallel_size: 8
      use_fast_tokenizer: True
      gpu_memory_utilization: 0.65
      max_running_requests: 64
      temperature: 1.0
      top_p: 0.95
      top_k: 20
      min_p: 0.0
      presence_penalty: 1.5
      repetition_penalty: 1.0
      generate_max_tokens: 2048

bt_rm:
  reward_type: "rule_only"
  reward_model_info:
    - model_arch: "qwen3_5_moe"
      hf_model_path: "hf-hub/Qwen/Qwen3.6-35B-A3B/"
      reward_py_path: tasks/math_rl_v4/bt_reward.py
      parse_reward_fn_name: math_rl_rule_reward
      reward_weight: 1.0
  infer_engine_configs:
    - dist_config:
        nnodes: -1

# dist_config.nnodes 设置 -1 表示适用所有节点

ppo:
  advantage_type: "grpo"
  grpo_advantage_epsilon: 1.0e-4
  ppo_ratio_eps: 0.2

debug:
  save_first_rollout_data: True
  debug_engine_update_weight: False
