# @package _global_
# 参数和 xh 的配置完全一样

training:
  training_backend: fsdp2
  use_gen_rm_reward: False
  use_bt_rm_reward: True
  rollout_gbs: 64
  rollout_mbs: 1
  rollout_model_mbs: 1
  train_gbs_wo_timestep: 256
  train_mbs: 1
  sampling_repeat_n: 12
  init_same_noise: True
  width: 1024
  height: 1024
  max_prompt_length: 256
  eta: 0.3
  sampling_steps: 16
  shift: 3
  data_parallel_random_init: True
  timestep_fraction: 0.6
  save_interval: 100
  num_train_epoches: 1
  enable_cfg: False
  guidance_scale: 1.0
  disable_cfg_uncond_grad: False

checkpoint:
  load_ckpt_path: t2i_ckpt/t2i_grpo_tv4_oteam4_4_wo_cfg_260105
  save_ckpt_path: t2i_ckpt/t2i_grpo_tv4_oteam4_4_wo_cfg_260105

optimizer:
  lr: 1e-5
  lr_warmup_steps: 0
  lr_decay_style: "constant_with_warmup"
  weight_decay: 0.0001
  max_grad_norm: 0.1

data:
  data_pathes:
    - "hf-hub/wechat/data/pcg_diamond_jsonl_50069.jsonl"
  py_path: "tasks/t2i_grpo_tv4/simple_dataset.py"
  fn_name: "get_dataset_and_dataloader"

policy:
  dist_config:
    nnodes: 8
  without_ref: true
  model_arch: "oteam4_4"
  hf_model_path: "hf-hub/wechat/oteam4_4-step-40000"
  ref_hf_model_path: "hf-hub/wechat/oteam4_4-step-40000"
  gen_rm_client:
    rpc_type: ray
  bt_rm_client:
    rpc_type: ray

bt_rm:
  dist_config:
    nnodes: 8
  reward_model_info:
    - model_arch: "wegen_hpsv3"
      model_weight_path: hf-hub/wechat/wegen_hpsv3/model.pth
      reward_weight: 1.0
      reward_py_path: tasks/t2i_grpo_tv4/wegen_hpsv3.py
      rm_cls_name: WegenHpsv3RewardModel
  infer_engine_configs:
    - dist_config:
        nnodes: 8

task:
  hpsv3_yaml_path: tasks/t2i_grpo_tv4/yaml/wegen_hpsv3_8B.yaml

ppo:
  grpo_advantage_epsilon: 1.0e-8
  ppo_ratio_eps: 1.0e-5
  adv_clip_max: 5.0
  adv_clip_min: -5.0

debug:
  save_images: True
  save_images_dir: debug_images_lxh
