# @package _global_
# 从 oteam4_4_rl_config_251211.yaml copy 过来，将 bt RM 修改为 gen RM。

training:
  training_backend: fsdp2
  use_gen_rm_reward: True
  use_bt_rm_reward: False
  rollout_gbs: 64
  rollout_mbs: 1
  rollout_model_mbs: 1
  train_gbs_wo_timestep: 256
  train_mbs: 1
  sampling_repeat_n: 12
  init_same_noise: True
  guidance_scale: 3.5
  width: 1024
  height: 1024
  max_prompt_length: 256
  eta: 0.3
  sampling_steps: 16
  shift: 3
  data_parallel_random_init: True
  timestep_fraction: 0.6
  save_interval: 100
  num_train_epoches: 1

checkpoint:
  load_ckpt_path: t2i_grpo_tv4_oteam4_4_save_251218
  save_ckpt_path: t2i_grpo_tv4_oteam4_4_save_251218

optimizer:
  lr: 1e-5
  lr_warmup_steps: 0
  lr_decay_style: "constant_with_warmup"
  weight_decay: 0.0001
  max_grad_norm: 0.1

data:
  data_pathes:
    - "hf-hub/wechat/data/cluster_30w_data.jsonl"
  py_path: "tasks/t2i_grpo_tv4/simple_dataset.py"
  fn_name: "get_dataset_and_dataloader"

policy:
  dist_config:
    nnodes: 8
  without_ref: true
  model_arch: "oteam4_4"
  hf_model_path: "hf-hub/wechat/oteam4_4-step-10000"
  ref_hf_model_path: "hf-hub/wechat/oteam4_4-step-10000"
  gen_rm_client:
    rpc_type: ray
  bt_rm_client:
    rpc_type: ray

gen_rm:
  backend: sglang
  dist_config:
    nnodes: 8
  reward_model_info:
    - model_arch: "qwen3_vl"
      hf_model_path: "hf-hub/Qwen/Qwen3-VL-235B-A22B-Instruct"
      reward_py_path: "tasks/t2i_grpo_tv4/gen_rewards.py"
      prompt_fn_name: "get_qwen3_vl_prompt"
      parse_reward_fn_name: "parse_qwen3_vl_rewards"
      reward_weight: 1.0
  infer_engine_configs:
    - dist_config:
        nnodes: 8
        tensor_model_parallel_size: 8
      use_fast_tokenizer: True
      gpu_memory_utilization: 0.7
      max_running_requests: 128
      temperature: 0.1
      top_p: 1.
      # xinhang leng 实际上是没有做长度限制的（也就是最大 256k），不过我肉眼看了下实际输出长度还好，
      # 考虑到 qwen3vl 偶发会有长尾，先改成 4k。或者 128k 131072 看看。
      generate_max_tokens: 4096

ppo:
  grpo_advantage_epsilon: 1.0e-8
  ppo_ratio_eps: 1.0e-4
  adv_clip_max: 5.0
  adv_clip_min: -5.0

debug:
  save_images: True
  save_images_dir: debug_images
