# @package _global_
# 从 oteam4_4_rl_config_251211.yaml copy 过来，没有任何改变，但是尝试 fix CFG 的实现。

training:
  training_backend: fsdp2
  use_gen_rm_reward: False
  use_bt_rm_reward: True
  rollout_gbs: 64
  rollout_mbs: 1
  rollout_model_mbs: 1
  train_gbs_wo_timestep: 768
  train_mbs: 1
  sampling_repeat_n: 12
  init_same_noise: True
  guidance_scale: 3.5
  width: 1024
  height: 1024
  max_prompt_length: 256
  eta: 0.3
  sampling_steps: 16
  shift: 3
  data_parallel_random_init: True
  timestep_fraction: 0.5
  save_interval: 100
  num_train_epoches: 1
  disable_cfg_uncond_grad: False

checkpoint:
  load_ckpt_path: t2i_grpo_tv4_oteam4_4_save_251219_no_skip
  save_ckpt_path: t2i_grpo_tv4_oteam4_4_save_251219_no_skip

optimizer:
  lr: 1e-5
  lr_warmup_steps: 0
  lr_decay_style: "constant_with_warmup"
  weight_decay: 0.0001
  max_grad_norm: 1.0

data:
  data_pathes:
    - "hf-hub/wechat/data/cluster_30w_data.jsonl"
  py_path: "tasks/t2i_grpo_tv4/simple_dataset.py"
  fn_name: "get_dataset_and_dataloader"

policy:
  without_ref: true
  model_arch: "oteam4_4"
  hf_model_path: "hf-hub/wechat/oteam4_4-step-10000"
  ref_hf_model_path: "hf-hub/wechat/oteam4_4-step-10000"
  gen_rm_client:
    rpc_type: ray
  bt_rm_client:
    rpc_type: ray

bt_rm:
  reward_model_info:
    - model_arch: "hpsv3"
      # hf_model_path: hf-hub/laion/CLIP-ViT-H-14-laion2B-s32B-b79K/open_clip_pytorch_model.bin
      # model_weight_path: hf-hub/xswu/HPSv2/HPS_v2.1_compressed.pt
      reward_weight: 1.0
      reward_py_path: tasks/t2i_grpo_tv4/my_hpsv3.py
      rm_cls_name: Hpsv3RewardModel
  infer_engine_configs:
    - dist_config:
        nnodes: -1

ppo:
  grpo_advantage_epsilon: 1.0e-8
  ppo_ratio_eps: 1.0e-2
  adv_clip_max: 5.0
  adv_clip_min: -5.0

debug:
  save_images: True
  save_images_dir: debug_images
