# @package _global_

training:
  training_backend: fsdp2
  use_gen_rm_reward: True
  total_training_step: 100
  rollout_gbs: 16
  sampling_repeat_n: 8
  init_same_noise: False
  guidance_scale: 3.5
  width: 720
  height: 720
  eta: 0.3
  sampling_steps: 2
  shift: 3
  data_parallel_random_init: False

# report_config:
#   report_to: "wandb"
# optimizer_config:
#   adam_beta1: 0.9
#   adam_beta2: 0.999
#   adam_epsilon: 1.0e-8
#   lr: 2e-5

data:
  data_pathes:
    - "tasks/t2i_grpo_tv4/prompts.txt"
  py_path: "tasks/t2i_grpo_tv4/simple_dataset.py"
  fn_name: "get_dataset_and_dataloader"

policy:
  dist_config:
    nnodes: 1
  model_arch: "flux"
  hf_model_path: "hf-hub/black-forest-labs/FLUX.1-dev"
  ref_hf_model_path: "hf-hub/black-forest-labs/FLUX.1-dev"
  gen_rm_client:
    rpc_type: ray
  without_ref: True

gen_rm:
  backend: sglang
  dist_config:
    nnodes: 1
  reward_model_info:
    - model_arch: "qwen2_5_vl"
      hf_model_path: "hf-hub/Qwen/Qwen2.5-VL-3B-Instruct"
      reward_py_path: "tasks/t2i_grpo_tv4/gen_rewards.py"
      prompt_fn_name: "get_qwen2_5_vl_prompt"
      parse_reward_fn_name: "parse_qwen2_5_vl_rewards"
    # - model_arch: "qwen2_5_vl"
    #   hf_model_path: "hf-hub/Qwen/Qwen2.5-VL-7B-Instruct"
    #   reward_py_path: tasks/t2i_grpo_tv4/reward_file.py
    #   prompt_fn_name: get_qwen2_5_vl_prompt
    #   parse_reward_fn_name: calculate_qwen2_5_vl_rewards

  infer_engine_configs:
    - dist_config:
        nnodes: 1
        tensor_model_parallel_size: 4
      use_fast_tokenizer: True
      gpu_memory_utilization: 0.7
      max_running_requests: 128
      temperature: 1.0
      top_p: 0.9
      generate_max_tokens: 1024
    # - dist_config:
    #     nnodes: 1
    #     tensor_model_parallel_size: 2
    #   use_fast_tokenizer: True
    #   gpu_memory_utilization: 0.7
    #   max_running_requests: 128
    #   temperature: 1.0
    #   top_p: 0.9
    #   generate_max_tokens: 1024

ppo:
  grpo_advantage_epsilon: 1e-8
