_target_: gpatch_v4.configs.config.OnPolicyDistillConfig

training:
  training_backend: mcore
  use_gen_rm_reward: False
  use_bt_rm_reward: True
  use_fast_tokenizer: True
  rollout_gbs: 128
  rollout_mbs: 1
  eval_interval: 5
  eval_before_train: True
  eval_rollout_gbs: 128
  eval_rollout_mbs: 1
  sampling_repeat_n: 5
  sampling_keep_n: 5
  train_gbs: 640
  seq_length: 8192
  data_parallel_random_init: False
  save_interval: 100
  metrics_report:
    - "acc_reward"
    - "fmt_reward"
  auto_load_from_save_ckpt: True
  num_train_epoches: 15
  build_from_mbridge: True

checkpoint:
  load_ckpt_path: ckpt_qwen3vl_onp_distill_ckpt
  save_ckpt_path: ckpt_qwen3vl_onp_distill_ckpt
  convert_mcore_to_hf_online: True
  mbridge_distributed_filesystem: True

optimizer:
  lr: 1.0e-6
  lr_warmup_steps: 0
  lr_decay_style: "constant"
  weight_decay: 0.0
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1.0e-8

data:
  data_pathes:
    - "hf-hub/hiyouga/geometry3k"
  eval_data_pathes:
    - "hf-hub/hiyouga/geometry3k"
  py_path: "tasks/multimodal_v4/on_policy_distill/qwen3vl_simple_dataset.py"
  fn_name: "get_dataset_and_dataloader"
  dataloader_num_workers: 4
  dataloader_pin_memory: True
  dataloader_prefetch_factor: 32
  # only for verify dataloader in gpatch_v4/entry/verify_dataloader.py
  dataloader_verify_fn_name: "verify_dataloader_func"

policy:
  dist_config:
    nnodes: -1
    tensor_model_parallel_size: 1
    pipeline_model_parallel_size: 1
  model_arch: "qwen3_vl"
  hf_model_path: "hf-hub/Qwen/Qwen3-VL-2B-Instruct"
  hf_tokenizer_path: "hf-hub/Qwen/Qwen3-VL-2B-Instruct"
  ref_hf_model_path: "hf-hub/Qwen/Qwen3-VL-2B-Instruct"
  rollout_gen_type: "on_policy_distill"
  sampler_client:
    rpc_type: ray
  teacher_client:
    rpc_type: ray
  bt_rm_client:
    rpc_type: ray

sampler:
  backend: sglang
  dist_config:
    nnodes: -1
    tensor_model_parallel_size: 2
  model_info:
    - model_arch: "qwen3_vl"
      hf_model_path: "hf-hub/Qwen/Qwen3-VL-2B-Instruct"

  infer_engine_configs:
    - dist_config:
        nnodes: -1
        tensor_model_parallel_size: 2
      gpu_memory_utilization: 0.7
      max_running_requests: 1024
      temperature: 1.0
      top_p: 0.9
      generate_max_tokens: 7168
      use_fast_tokenizer: True

teacher:
  dist_config:
    nnodes: -1
    tensor_model_parallel_size: 4
    pipeline_model_parallel_size: 1
  model_arch: "qwen3_vl"
  hf_model_path: "hf-hub/Qwen/Qwen3-VL-32B-Instruct"
  hf_tokenizer_path: "hf-hub/Qwen/Qwen3-VL-32B-Instruct"
  wrap_with_ddp: False

bt_rm:
  dist_config:
    nnodes: -1
  reward_type: "rule_only"
  reward_model_info:
    - model_arch: "qwen3_vl"
      hf_model_path: "hf-hub/Qwen/Qwen3-VL-2B-Instruct"
      reward_py_path: tasks/multimodal_v4/on_policy_distill/bt_reward.py
      parse_reward_fn_name: geo3k_rl_rule_reward
      reward_weight: 1.0
  infer_engine_configs:
    - dist_config:
        nnodes: -1

ppo:
  advantage_type: "on_policy_distill"
  distill_kl_penalty_coef: 1.0
  distill_kl_discount_factor: 0.0
  ppo_ratio_eps: 0.2
  grpo_kl_loss_beta: 0.0
  ppo_entropy_bonus: 0.0

debug:
  save_first_rollout_data: True
  debug_engine_update_weight: False
